### ISSUE TITLE
Cancel URL return querystring parameter

### ISSUE THREAD

**Issue by JontyStephan** [louislewis2/payfast#10]
I have followed your https://github.com/louislewis2/payfast/tree/master/samples/PayFast.Web.Net code and when the cancel button is clicked on the Payfast payments page, the browser redirects back to my cancel URL with a ?pt= querystring appended e.g. http://myurl/home/cancel?pt=8d70f413-c216-8a4b-b5ef-30ebfdf3cd82. Can you please let me know what this is?

**Comment by louislewis2** [comment]
Sorry for such an insane delay, I missed this issue completely, apologies. 
If I remember correctly, it is the identifier you supply for the payment request.
Let me know if you still need more details.
