### ISSUE TITLE
ApiResponseException httpResponseMessage content unreadable due to httpClient being disposed

### ISSUE THREAD

**Issue by TechnoDezi** [louislewis2/payfast#21]
Hi @louislewis2 and @francoishill 

I picked up a bug which is quite urgent. I have a system in production and the addHock charge of a token is failing and to debug I need to read the httpResponseMessage content of the ApiResponseException.

But due to the fact that httpClient gets disposed of before I get a chance to read this, I am unable to read the content of the response message.

Can I extend/change this ApiResponseException to rather store the Content alongside the httpResponseMessage as a string property and submit a Pull Request for you?

**Comment by louislewis2** [comment]
Hi there,

The contents of the exception should not be affected by the disposal of the HttpClient.
Would it be possible to create a tiny repo with an example of this happening or something that I could look at?

We recently debugged issues using the exception without any issues.

**Comment by TechnoDezi** [comment]
Hi

Thanks for the help @louislewis2 . V1.0.5 allows me now to read the response message.
